server:
  port: 8080
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_espinoza
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

security:
  jwt:
    secret: MiSuperClaveParaElExamenT2123456789!@$#
    expiration: 3600000